Skills= {
    'Data Science':             ['python','machine learning','deep learning','pandas',
                                  'numpy','tensorflow','pytorch','sql','statistics',
                                  'scikit-learn','matplotlib','seaborn','nlp'],
    'Python Developer':         ['python','django','flask','fastapi','rest api','sql',
                                  'git','docker','celery','redis','postgresql'],
    'Java Developer':           ['java','spring','hibernate','maven','microservices',
                                  'sql','junit','docker','rest api','kafka'],
    'DevOps Engineer':          ['docker','kubernetes','ci/cd','jenkins','aws','linux',
                                  'terraform','ansible','git','prometheus','grafana'],
    'Web Designing':            ['html','css','javascript','react','figma','ui/ux',
                                  'bootstrap','responsive design','photoshop','sass'],
    'Testing':                  ['selenium','manual testing','automation','jira',
                                  'test cases','api testing','postman','pytest','qa'],
    'Automation Testing':       ['selenium','appium','pytest','robot framework',
                                  'jenkins','ci/cd','java','python','testng'],
    'Database':                 ['sql','mysql','postgresql','mongodb','oracle',
                                  'redis','elasticsearch','data modeling','etl'],
    'Business Analyst':         ['requirements gathering','uml','jira','sql',
                                  'power bi','excel','stakeholder management','agile'],
    'HR':                       ['recruitment','onboarding','payroll','hrms',
                                  'performance management','communication','excel'],
    'Network Security Engineer':['firewalls','vpn','intrusion detection','tcp/ip',
                                  'penetration testing','siem','python','linux'],
    'Blockchain':               ['solidity','ethereum','smart contracts','web3',
                                  'cryptography','python','javascript','defi'],
    'Hadoop':                   ['hadoop','spark','hive','hdfs','mapreduce',
                                  'scala','kafka','python','sql'],
    'Cloud':                    ['aws','azure','gcp','docker','kubernetes',
                                  'terraform','linux','networking'],
    'Mechanical Engineer':      ['autocad','solidworks','ansys','thermodynamics',
                                  'manufacturing','catia','matlab'],
    'Civil Engineer':           ['autocad','staad pro','revit','structural analysis',
                                  'surveying','estimation','ms project'],
    'Electrical Engineering':   ['matlab','plc','scada','circuit design','autocad',
                                  'power systems','embedded systems'],
    'Sales':                    ['crm','salesforce','negotiation','lead generation',
                                  'communication','excel','target achievement'],
    'Operations Manager':       ['supply chain','logistics','erp','six sigma',
                                  'lean','excel','project management','kpi'],
}
category_map = {
    0: 'Advocate',
    1: 'Arts',
    2: 'Automation Testing',
    3: 'Blockchain',
    4: 'Business Analyst',
    5: 'Civil Engineer',
    6: 'Data Science',
    7: 'Database',
    8: 'DevOps Engineer',
    9: 'DotNet Developer',
    10: 'Electrical Engineering',
    11: 'HR',
    12: 'Hadoop',
    13: 'Health and fitness',
    14: 'Java Developer',
    15: 'Mechanical Engineer',
    16: 'Network Security Engineer',
    17: 'Operations Manager',
    18: 'PMO',
    19: 'Python Developer',
    20: 'SAP Developer',
    21: 'Sales',
    22: 'Testing',
    23: 'Web Designing'
}